LOAD DATA
INFILE 'prodCompra.csv'
INTO TABLE PROD_COMPRA
FIELDS TERMINATED BY ';'
(
    COD_USUARIO INTEGER EXTERNAL,
    NRO_COMPRA INTEGER EXTERNAL,
    COD_PRODUCTO INTEGER EXTERNAL,
    PRECIO_UNITARIO INTEGER EXTERNAL,
    CANTIDAD INTEGER EXTERNAL
)
