OPTIONS (SKIP=0)
LOAD DATA
    INFILE 'temas.csv' "str '\r\n'"
    APPEND INTO TABLE TEMA
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    TRAILING NULLCOLS
( COD_TEMA,
  NOMBRE CHAR(100) )
