OPTIONS (SKIP=0)
LOAD DATA
    INFILE 'usuarios-2.csv' "str '\r\n'"
    APPEND INTO TABLE USUARIO
    FIELDS TERMINATED BY ';'
    TRAILING NULLCOLS
( COD_USUARIO "usuario_seq.NEXTVAL",
  NOMBRE_USUARIO,
  NOMBRES,
  APELLIDOS,
  CORREO,
  CONTRASENA,
  DIRECCION,
  CIUDAD )
