INSERT INTO Pais (COD_PAIS, NOMBRE_PAIS) VALUES (169, 'Colombia');
INSERT INTO Pais (COD_PAIS, NOMBRE_PAIS) VALUES (249, 'Estados Unidos');
INSERT INTO Pais (COD_PAIS, NOMBRE_PAIS) VALUES (063, 'Argentina');
INSERT INTO Pais (COD_PAIS, NOMBRE_PAIS) VALUES (105, 'Brasil');
INSERT INTO Pais (COD_PAIS, NOMBRE_PAIS) VALUES (275, 'Francia');
INSERT INTO Pais (COD_PAIS, NOMBRE_PAIS) VALUES (023, 'Alemania');

COMMIT; -- Para guardar los cambios en la base de datos

INSERT INTO Ciudad (COD_CIUDAD, NOMBRE_CIUDAD)  
SELECT codCiudad, nombreCiudad FROM DATABASE35.ciudad;
COMMIT;
SELECT COUNT(*) FROM Ciudad;

-- SQL loader
DESC categoria;
SELECT COUNT(*) FROM categoria; 
DESC producto;
SELECT COUNT(*) FROM producto;
DESC tema;
SELECT COUNT(*) FROM tema;
DESC tema_producto;
SELECT COUNT(*) FROM tema_producto;
CREATE SEQUENCE usuario_seq START WITH 1 INCREMENT BY 1;
SELECT MIN(COD_USUARIO) AS MIN_COD, MAX(COD_USUARIO) AS MAX_COD, COUNT(*) AS TOTAL
FROM USUARIO;

--SQL DEVELOPER
SELECT COUNT(*) FROM CARRITO_COMPRAS;
SELECT COUNT(*) FROM COMPRA;
SELECT COUNT(*) FROM ELIMINADOS;

--SQL loader
SELECT COUNT(*) FROM PROD_COMPRA;